services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      TZ: Asia/Tokyo
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
